import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/provider/ReduxProvider";

const urbanist = Urbanist({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "ProFast",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${urbanist.className} bg-background`}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
